version: "3.8"
services:
    backend:
        build: ./backend
        ports:
            - "8000:8000"
    frontend:
        build: ./qr-front
        ports:
            - "80:80"
        env_file:
            - ./qr-front/.env
